### ISSUE TITLE
Cant execute jar files on Linux

### ISSUE THREAD

**Issue by ratzupaltuff** [weisJ/Mima#15]
I cannot execute the jar files from the build folder. Im running on Arch Linux with OpenJDK 10&11. I get the following error:

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bulenkov.darcula.DarculaLaf (file:/home/ratzupaltuff/Downloads/Mima-1.6.jar) to field javax.swing.text.html.HTMLEditorKit.DEFAULT_STYLES_KEY
WARNING: Please consider reporting this to the maintainers of com.bulenkov.darcula.DarculaLaf
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bulenkov.iconloader.IconLoader.<clinit>(IconLoader.java:53)
	at com.bulenkov.darcula.DarculaLaf.getDefaults(DarculaLaf.java:97)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:632)
	at edu.kit.mima.App.main(App.java:25)
Caused by: java.lang.NullPointerException
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 5 more``

Do you know this error? Thank you in advance.

**Comment by weisJ** [comment]
What version of the jar are you running?
The first part of the error is expected and shouldn't affect the program.
Could you please try this version and let me know whether it works for you:
https://1drv.ms/u/s!As_jhofqXRMH5hVMIH9C91qsm-TG

**Comment by ratzupaltuff** [comment]
I tried executing the jar with java-10-openjdk and java-11-openjdk. With the file from the Onedrive link the program works with java-10-openjdk (I have not tested java-11). Thank you very much.
